// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptjkyznaceuebsyxhlig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0amt5em5hY2V1ZWJzeXhobGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzAzMzgsImV4cCI6MjA2MDcwNjMzOH0.sXmehLTugpy8ufK3Xfmm8tM4NtrVELipdthgrLG84I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);